# Generated by Django 5.2.5 on 2025-08-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('fingerprint_hash', models.CharField(max_length=255)),
                ('boundary_partner', models.CharField(blank=True, max_length=255, null=True)),
                ('progress_marker_status', models.JSONField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
    ]
